PROCEDURE pres_mvt
clear
@ 1,0 TO 22,79 
@ 0,32 TO 2,47 
@ 1,33 SAY " MVT DE STOCK " 
@ 2,2 SAY "le " 
@ 2,5 SAY date() 
@ 4,0 TO 4,79 
@ 4,0 SAY "Ã" 
@ 4,9 TO 22,9 
@ 4,9 SAY "Â" 
@ 4,34 TO 22,34 
@ 4,34 SAY "Â" 
@ 4,40 TO 22,40 
@ 4,40 SAY "Â" 
@ 4,46 TO 22,46 
@ 4,46 SAY "Â" 
@ 4,51 TO 22,51 
@ 4,51 SAY "Â" 
@ 4,56 TO 22,56 
@ 4,56 SAY "Â" 
@ 4,65 TO 22,65 
@ 4,65 SAY "Â" 
@ 4,79 SAY "´" 
@ 5,2 SAY "Article" 
@ 5,10 SAY "D‚signation" 
@ 5,36 SAY "Manq" 
@ 5,42 SAY "Ven" 
@ 5,47 SAY "Phys" 
@ 5,52 SAY "Comd" 
@ 5,59 SAY "B/O" 
@ 5,67 SAY "Prix vente" 
@ 6,0 TO 6,79 
@ 6,0 SAY "Ã" 
@ 6,9 SAY "Å" 
@ 6,34 SAY "Å" 
@ 6,40 SAY "Å" 
@ 6,46 SAY "Å" 
@ 6,51 SAY "Å" 
@ 6,56 SAY "Å" 
@ 6,65 SAY "Å" 
@ 6,79 SAY "´" 
@ 22,9 SAY "Á" 
@ 22,34 SAY "Á" 
@ 22,40 SAY "Á" 
@ 22,46 SAY "Á" 
@ 22,51 SAY "Á" 
@ 22,56 SAY "Á" 
@ 22,65 SAY "Á" 

return
